[package]
    name = "typmind"
    version = "0.1.0"
    compiler = "0.13.0"
    repository = "https://github.com/ivaquero/typmind.git"
    entrypoint = "src/lib.typ"
    authors = ["ivaquero"]
    license = "MIT"
    description = "Turn files csv into mindmaps."
    categories = ["layout"]
    keywords = ["mindmap"]
